version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    networks:
      - documind-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - ../.env
    command: streamlit run frontend/main.py
    volumes:
      - ../data:/app/data
    networks:
      - documind-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-documind}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-documind}
      POSTGRES_DB: ${POSTGRES_DB:-documind}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - documind-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - documind-network

networks:
  documind-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
